// <auto-generated />
namespace TicketSysteemMVC5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TicketDatum_TicketStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TicketDatum_TicketStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201905160938559_Ticket-Datum_Ticket-Status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
